### ISSUE TITLE
Link to map doesn't use specified port

### ISSUE THREAD

**Issue by samstreak** [dkilgore90/iRobot#21]
https://github.com/dkilgore90/iRobot/blob/cee044600aee58b9741e841b69268d30f5a2b97d/Roomba/Roomba-app.groovy#L263

3000     on line 263 should be replaced by   ${doritaPort}

**Comment by dkilgore90** [comment]
thx for the report! will be fixed in the next release

**Comment by samstreak** [comment]
Thanks for the quick response!  Maybe I'm one of the 'weird' ones that don't/can't use the standard port   :)     I have Assistant Relay running on 3000 already
