### ISSUE TITLE
Starting outside of set times, presence change while charging does nothing

### ISSUE THREAD

**Issue by riceburner24** [dkilgore90/iRobot#7]
I have my iRobot set to clean Mon thru Fri at 10am, if presence is detected, delay 120 minutes, if still present, cancel until next cleaning time.  For some reason if presence leaves after at any point after 10am it will start cleaning (ex. 11am, 1pm).

Also, if the robot is charging but not completed its job and presence is detected, it will finish charging and continue the job.  It should just stay on the dock and finish the job.

This app is amazing!

**Comment by dkilgore90** [comment]
@riceburner24 -- looking over the presence data -- could you add some screenshots of your App settings -- particularly in the Presence Options section? This will help me trace the exact code paths your sequence should be following

**Comment by riceburner24** [comment]
@dkilgore90 
![Roomba Dashboard and Logging Options](https://user-images.githubusercontent.com/72715219/109584120-feb41b00-7ace-11eb-85ec-43d6ace6d594.jpg)
![iRobot Scheduler Logs](https://user-images.githubusercontent.com/72715219/109584122-feb41b00-7ace-11eb-8a76-829a23ed3ea5.jpg)
![Roomba Connection and Notification](https://user-images.githubusercontent.com/72715219/109584123-feb41b00-7ace-11eb-86a6-34d7de28830b.jpg)
![Roomba Schedule](https://user-images.githubusercontent.com/72715219/109584126-ff4cb180-7ace-11eb-931c-31308af9f4e3.jpg)
![Roomba Presence Options](https://user-images.githubusercontent.com/72715219/109584127-ff4cb180-7ace-11eb-859e-ce2f244d1341.jpg)
![Roomba Advanced Options](https://user-images.githubusercontent.com/72715219/109584128-ff4cb180-7ace-11eb-907a-3c3dbba4ccb5.jpg)

**Comment by riceburner24** [comment]
@dkilgore90 I had to take individual screen shots so they are a bit out of order.  Also included a recent time where it ran on a Saturday after presence was not detected.  Seems like if both my wife and I leave (combined presence) it starts no matter what day of the week or time of day.

The second issue is very specific and I do not have a log of it right now.  If it is cleaning, has to return to the dock to charge, and someone comes home (while it is on the dock charging), it will continue to clean after it charges to the set amount (ignoring the change in presence)

**Comment by dkilgore90** [comment]
The second half of this issue should be addressed by the merge of #14 -- LMK if you notice this still occurs.

As to the first half, from a review of the code, the `roombaPresenceDelay` setting should be a "maximum" delay -- e.g. if Presence is detected at the scheduled cleaning time, it will wait _up to_ that number of minutes for presence to leave.  If presence departs within that time window, cleaning begins immediately -- if not, cleaning should be deferred to the next day.  Does that match what occurs for your case?

**Comment by riceburner24** [comment]
I have updated to 1.4.6 and will update you on what happens when returning home while Roomba is on the dock.

The time delay hasn't been an issue, so I haven't paid as close attention to it since I posted originally.  I will keep a close eye on this and give an update when that scenario occurs again.

Also, I had to add a ")" on line 921 after the other three ")".  It wouldn't let me save the code without it.  I think that was the correct spot.

**Comment by dkilgore90** [comment]
whoops -- thanks for pointing out the error on line 921 -- that'll teach me to push new code without testing it first :)

pushed 1.4.7 with the extra `)` so that it saves correctly

**Comment by riceburner24** [comment]
Here is an example from today.  First time to start was 10:00AM, delay 120 min if necessary.  All presence was departed and started cleaning at 8:37AM.  This is not a big deal for me because it works out anyway.  The stop cleaning while charging does work now!  It happened today and worked perfectly.
![image](https://user-images.githubusercontent.com/72715219/124047064-50b76f80-d9e1-11eb-9981-343a73521312.png)

**Comment by riceburner24** [comment]
I don't know what changed, but it is now waiting until 10:00AM to start cleaning.  However, if it has to charge before completing the house it cancels cleaning completely.
An example, screenshots from my phone notifications.  It was fully charged before my wife came home, iRobot app said cleaning was canceled.
![Screenshot_20210713-151045](https://user-images.githubusercontent.com/72715219/125711001-e2f97c11-ee6a-47dc-8bf7-cb68befc1efb.png)
![Screenshot_20210713-151010](https://user-images.githubusercontent.com/72715219/125711020-af523a45-9bf1-4828-b6de-fae3e8277704.png)

**Comment by dkilgore90** [comment]
Circling back to this - I see it reported "bin full" at 10:40, then "stopped cleaning" at 11:05, "charging" at 11:06. This last issue _might_ be related to be the `dock based on battery percentage` setting - the "dock" command is considered termination of the job.

Depending on the model Roomba you have, this might not be required...

**Comment by riceburner24** [comment]
I know it has been awhile, but I have time to get back into this issue.  I will try and be more responsive and help debug.  Here is the log and current settings of a cleaning that happened today, the last two entries are when I manually stopped it because it started after I returned home.  (it was charging when I arrived home)

My goal is to have it clean whenever I leave, no matter the time or day of the week and stop when I get home.  If my settings need to be tweaked, let me know.

<img width="553" alt="Roomba Logs 7-23-22" src="https://user-images.githubusercontent.com/72715219/180621356-54e31288-0515-4291-99d1-278780c31413.png">
<img width="562" alt="Roomba Settings1" src="https://user-images.githubusercontent.com/72715219/180621361-49b08fbe-a2ec-4133-89d7-143aac1d7f52.png">
<img width="737" alt="Roomba Settings2" src="https://user-images.githubusercontent.com/72715219/180621365-eb7f575c-b581-4e02-aaa9-c5979956e157.png">

**Comment by dkilgore90** [comment]
Hmm, `12:42:02.413pm Docking Randy based on presence options` indicates that the logic to end the run (and dock) when you arrived home _was_ triggered.

Then at 01:16pm it starts cleaning again... May need to add more debug logs to capture the full robot state in order to run this down...

**Comment by riceburner24** [comment]
Let me know how I can help.

**Comment by dkilgore90** [comment]
Just published app v1.6.1 which includes a new "Verbose state change logging" preference -- this will dump the entire JSON from dorita980 when it detects the cleanStatus changed.  If you can enable that (and set log minutes to 0), then try to provoke the issue again... I realize it's a tricky spot to hit -- middle of cycle, charging, then presence arrives.

**Comment by riceburner24** [comment]
Updated and enabled, if all else fails I will create a virtual presence that I can control to recreate the issue.

**Comment by riceburner24** [comment]
Since this hasn't happened naturally I forced the issue today with a virtual presence.  Here is the log surrounding when I triggered presence as arrived.  The robot had been cleaning for about an hour and was on charge for about 20 minutes when I triggered the arrival.  You may need to walk me through how to get the dorita980 JSON if you need that.
![image](https://user-images.githubusercontent.com/72715219/182200607-f195c86d-c776-4739-bc9e-15b378359186.png)

**Comment by dkilgore90** [comment]
Argh -- I screwed up the `trace` logs -- fixed in 1.6.2.

I see the state transition after `Docking Randy` (within 1s) to "Cleaning" -- then within a minute back to "Charging" -- did it actually move back off the dock?  On 07/23 we also see this quick transition at 12:42-43 -- then it starts up again at 01:16.  The latter event is what I consider the larger problem, yes?

**Comment by riceburner24** [comment]
Updated and tested again this evening.  
Yes, the latter event is the issue.  I was home this time when I triggered the arrival and the dock immediately spun up and emptied the bin but it never moved off the dock.  (I feel this is good behavior, even though it may have emptied when it went to charge)   Here are the logs (overlapped by 2 events for clarity), they are getting lengthy so if there is a better way to get them to you, let me know
![Log3](https://user-images.githubusercontent.com/72715219/182277553-67d377fd-c9a2-4217-add2-897feb1bd312.jpg)
![Log2](https://user-images.githubusercontent.com/72715219/182277560-16ff2f10-7351-4ec4-93c2-291cf29f8d46.jpg)
![Log1](https://user-images.githubusercontent.com/72715219/182277573-d0c49336-249a-40e4-8f7a-c415ef934440.jpg)

**Comment by riceburner24** [comment]
Here is the log of when it started cleaning again.
![Log4](https://user-images.githubusercontent.com/72715219/182278833-5dd68458-88ef-4416-b8f8-912fc0c5a338.jpg)

**Comment by dkilgore90** [comment]
Thanks -- that helps -- throughout the charging time, it still shows `cleanMissionStatus.cycle: clean` -- with the same `mssnStrtTime` and `missionId`.  Which further confirms that it never terminated the job -- I think I'm going to throw in a `stop()` command as well -- hopefully the combination helps to terminate the job.

**Comment by dkilgore90** [comment]
ok -- try 1.6.3

**Comment by riceburner24** [comment]
I think that fixed it.  When I trigger the virtual presence as arrive while it is charging it makes a noise and does not start back up.  The app shows ready to clean rather than "will resume in"

Thanks for the help.  My next project is the ordered cleaning.

Here are the logs in case you want them.
![New Log 3](https://user-images.githubusercontent.com/72715219/183228256-b773755f-067e-4898-8485-51cf6c26e333.jpg)
![New Log 2](https://user-images.githubusercontent.com/72715219/183228259-70fad572-f2b5-43d2-87b0-9937b6bc98b3.jpg)
![New Log 1](https://user-images.githubusercontent.com/72715219/183228268-baa69dd9-aa38-4f70-9c84-65ca28360590.jpg)

**Comment by dkilgore90** [comment]
good deal! will close this issue
